F="s|bank[0-9]\+/img/\([a-zA-Z0-9_ -]\+\)\.png|bank19/img/19-"
T=".png|g"

cat knytt/objects/bank2/Flything.tscn | sed -e "$F"1"$T" > knytt/objects/bank19/base/Creature1.tscn
cat knytt/objects/bank2/BadFlything.tscn | sed -e "$F"2"$T" > knytt/objects/bank19/base/Creature2.tscn
cat knytt/objects/bank2/HomingFlything.tscn | sed -e "$F"3"$T" > knytt/objects/bank19/base/Creature3.tscn
cat knytt/objects/bank2/CaveFirefly.tscn | sed -e "s|bank2/img/\([a-z0-9_]\+\)\.png|bank19/img/\1.png|g" > knytt/objects/bank19/base/Creature4.tscn
cat knytt/objects/bank2/TentacleFlything.tscn | sed -e "$F"5"$T" > knytt/objects/bank19/base/Creature5.tscn
cat knytt/objects/bank2/PropellerChild2.tscn | sed -e "$F"6"$T" > knytt/objects/bank19/base/Creature6.tscn
cat knytt/objects/bank2/FlySpike1.tscn | sed -e "$F"7"$T" > knytt/objects/bank19/base/Creature7.tscn
cat knytt/objects/bank2/Birdie1.tscn | sed -e "$F"8"$T" > knytt/objects/bank19/base/Creature8.tscn
cat knytt/objects/bank2/Birdie3.tscn | sed -e "$F"9"$T" > knytt/objects/bank19/base/Creature9.tscn
cat knytt/objects/bank2/SnowBird.tscn | sed -e "$F"10"$T" > knytt/objects/bank19/base/Creature10.tscn
cat knytt/objects/bank2/CircleBird.tscn | sed -e "$F"11"$T" > knytt/objects/bank19/base/Creature11.tscn
cat knytt/objects/bank3/Muff3.tscn | sed -e "$F"12"$T" > knytt/objects/bank19/base/Creature12.tscn
cat knytt/objects/bank3/YellowDog.tscn | sed -e "$F"13"$T" > knytt/objects/bank19/base/Creature13.tscn
cat knytt/objects/bank3/SpikerMuff6.tscn | sed -e "$F"14"$T" > knytt/objects/bank19/base/Creature14.tscn
cat knytt/objects/bank3/Muff7.tscn | sed -e "$F"15"$T" > knytt/objects/bank19/base/Creature15.tscn
cat knytt/objects/bank3/Muff9.tscn | sed -e "$F"16"$T" > knytt/objects/bank19/base/Creature16.tscn
cat knytt/objects/bank3/Muff17.tscn | sed -e "$F"17"$T" > knytt/objects/bank19/base/Creature17.tscn
cat knytt/objects/bank3/Muff19.tscn | sed -e "$F"18"$T" > knytt/objects/bank19/base/Creature18.tscn
cat knytt/objects/bank3/Muff24.tscn | sed -e "$F"19"$T" > knytt/objects/bank19/base/Creature19.tscn
cat knytt/objects/bank3/Ratlike.tscn | sed -e "$F"20"$T" > knytt/objects/bank19/base/Creature20.tscn
cat knytt/objects/bank3/Muff34.tscn | sed -e "$F"21"$T" > knytt/objects/bank19/base/Creature21.tscn
cat knytt/objects/bank3/BigCat.tscn | sed -e "$F"22"$T" > knytt/objects/bank19/base/Creature22.tscn
cat knytt/objects/bank4/SixLegChild.tscn | sed -e "$F"23"$T" > knytt/objects/bank19/base/Creature23.tscn
cat knytt/objects/bank4/CeilingDropCrawler.tscn | sed -e "$F"24"$T" > knytt/objects/bank19/base/Creature24.tscn
cat knytt/objects/bank4/LeftStranger.tscn | sed -e "$F"25"$T" > knytt/objects/bank19/base/Creature25.tscn
cat knytt/objects/bank4/StrangeRunner.tscn | sed -e "$F"26"$T" > knytt/objects/bank19/base/Creature26.tscn
cat knytt/objects/bank4/HomingRunner.tscn | sed -e "$F"27"$T" > knytt/objects/bank19/base/Creature27.tscn
cat knytt/objects/bank4/ToastMonster.tscn | sed -e "$F"28"$T" > knytt/objects/bank19/base/Creature28.tscn
cat knytt/objects/bank4/TriShot.tscn | sed -e "$F"29"$T" > knytt/objects/bank19/base/Creature29.tscn
cat knytt/objects/bank4/RightSuperStranger.tscn | sed -e "$F"30"$T" > knytt/objects/bank19/base/Creature30.tscn
cat knytt/objects/bank6/Eater.tscn | sed -e "$F"31"$T" > knytt/objects/bank19/base/Creature31.tscn
cat knytt/objects/bank6/SelfDropper.tscn | sed -e "$F"32"$T" > knytt/objects/bank19/base/Creature32.tscn
cat knytt/objects/bank6/UpStuffShooter.tscn | sed -e "$F"33"$T" > knytt/objects/bank19/base/Creature33.tscn
cat knytt/objects/bank9/RedTrapFlower.tscn | sed -e "$F"34"$T" > knytt/objects/bank19/base/Creature34.tscn
cat knytt/objects/bank9/TimedFlower.tscn | sed -e "$F"35"$T" > knytt/objects/bank19/base/Creature35.tscn
cat knytt/objects/bank9/SmallTimedFlower.tscn | sed -e "$F"36"$T" > knytt/objects/bank19/base/Creature36.tscn
cat knytt/objects/bank10/TeenageFluff.tscn | sed -e "$F"37"$T" > knytt/objects/bank19/base/Creature37.tscn
cat knytt/objects/bank11/ShockDisk2.tscn | sed -e "$F"38"$T" > knytt/objects/bank19/base/Creature38.tscn
cat knytt/objects/bank11/GreenDisk.tscn | sed -e "$F"39"$T" > knytt/objects/bank19/base/Creature39.tscn
cat knytt/objects/bank11/ShockDisk3.tscn | sed -e "$F"40"$T" > knytt/objects/bank19/base/Creature40.tscn
cat knytt/objects/bank14/GreenWorm.tscn | sed -e "$F"41"$T" > knytt/objects/bank19/base/Creature41.tscn
cat knytt/objects/bank14/HarmlessInsect.tscn | sed -e "$F"42"$T" > knytt/objects/bank19/base/Creature42.tscn
cat knytt/objects/bank14/StationaryRock.tscn | sed -e "$F"43"$T" > knytt/objects/bank19/base/Creature43.tscn
cat knytt/objects/bank14/SmileBall.tscn | sed -e "$F"44"$T" > knytt/objects/bank19/base/Creature44.tscn
cat knytt/objects/bank14/AnotherSnail.tscn | sed -e "$F"45"$T" > knytt/objects/bank19/base/Creature45.tscn
cat knytt/objects/bank14/SpikelessSpiker.tscn | sed -e "$F"46"$T" > knytt/objects/bank19/base/Creature46.tscn
cat knytt/objects/bank14/SuperShotRight.tscn | sed -e "$F"47"$T" > knytt/objects/bank19/base/Creature47.tscn
cat knytt/objects/bank17/DarkRandomizer.tscn | sed -e "$F"48"$T" > knytt/objects/bank19/base/Creature48.tscn
cat knytt/objects/bank17/SmallSpider.tscn | sed -e "$F"49"$T" > knytt/objects/bank19/base/Creature49.tscn
cat knytt/objects/bank18/WaterMonster.tscn | sed -e "$F"50"$T" > knytt/objects/bank19/base/Creature50.tscn
