PATTERN="s/bank[0-9]\+\(\/[a-z_]\+\)\?\/\([a-zA-z0-9_]\+\)\.png/bank19\/img\/\2\.png/g"
cat knytt/objects/banks/bank2/CircleBird.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature11.tscn
cat knytt/objects/banks/bank3/Muff3.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature12.tscn
cat knytt/objects/banks/bank3/YellowDog.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature13.tscn
cat knytt/objects/banks/bank3/SpikerMuff6.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature14.tscn
cat knytt/objects/banks/bank3/Muff7.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature15.tscn
cat knytt/objects/banks/bank3/Muff9.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature16.tscn
cat knytt/objects/banks/bank3/Muff17.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature17.tscn
cat knytt/objects/banks/bank3/Muff19.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature18.tscn
cat knytt/objects/banks/bank3/Muff24.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature19.tscn
cat knytt/objects/banks/bank3/Ratlike.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature20.tscn
cat knytt/objects/banks/bank3/Muff34.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature21.tscn
cat knytt/objects/banks/bank3/BigCat.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature22.tscn
cat knytt/objects/banks/bank4/ToastMonsterNew.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature28.tscn
cat knytt/objects/banks/bank6/Eater.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature31.tscn
cat knytt/objects/banks/bank6/SelfDropper.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature32.tscn
cat knytt/objects/banks/bank6/UpStuffShooter.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature33.tscn
cat knytt/objects/banks/bank9/RedTrapFlower.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature34.tscn
cat knytt/objects/banks/bank9/TimedFlower.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature35.tscn
cat knytt/objects/banks/bank9/SmallTimedFlower.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature36.tscn
cat knytt/objects/banks/bank10/TeenageFluff.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature37.tscn
cat knytt/objects/banks/bank11/ShockDisk2.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature38.tscn
cat knytt/objects/banks/bank11/GreenDisk.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature39.tscn
cat knytt/objects/banks/bank11/ShockDisk3.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature40.tscn
cat knytt/objects/banks/bank14/GreenWorm.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature41.tscn
cat knytt/objects/banks/bank14/HarmlessInsect.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature42.tscn
cat knytt/objects/banks/bank14/StationaryRock.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature43.tscn
cat knytt/objects/banks/bank14/AnotherSnail.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature45.tscn
cat knytt/objects/banks/bank14/SpikelessSpiker.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature46.tscn
cat knytt/objects/banks/bank17/SmallSpider.tscn | sed -e $PATTERN > knytt/objects/banks/bank19/base/Creature49.tscn
